//
//  Countries.swift
//  ScoopTest
//
//  Created by Art Ostin on 19/06/2025.
//

import SwiftUI
import Foundation


struct CountryData: Identifiable {
    let flag: String
    let name: String
    
    var id: String {name}
}

class CountryDataServices {
    
    static let shared = CountryDataServices ()
    
    
    let popularCountries: [CountryData] = [
        .init(flag: "🇨🇦", name: "Canada"),
        .init(flag: "🇺🇸", name: "U.S."),
        .init(flag: "🇫🇷", name: "France"),
        .init(flag: "🇨🇳", name: "China"),
        .init(flag: "🇬🇧", name: "U.K."),
        .init(flag: "🇮🇳", name: "India"),
        .init(flag: "🇮🇷", name: "Iran"),
        .init(flag: "🇲🇽", name: "Mexico")
      ]
    
    let allCountries: [CountryData] = [
        CountryData(flag: "🇦🇫", name: "Afghanistan"),
        CountryData(flag: "🇦🇱", name: "Albania"),
        CountryData(flag: "🇩🇿", name: "Algeria"),
        CountryData(flag: "🇦🇩", name: "Andorra"),
        CountryData(flag: "🇦🇴", name: "Angola"),
//        CountryData(flag: "🇦🇬", name: "Antigua and Barbuda"),
        CountryData(flag: "🇦🇷", name: "Argentina"),
        CountryData(flag: "🇦🇲", name: "Armenia"),
        CountryData(flag: "🇦🇺", name: "Australia"),
        CountryData(flag: "🇦🇹", name: "Austria"),
        CountryData(flag: "🇦🇿", name: "Azerbaijan"),
        CountryData(flag: "🇧🇸", name: "Bahamas"),
        CountryData(flag: "🇧🇭", name: "Bahrain"),
        CountryData(flag: "🇧🇩", name: "Bangladesh"),
        CountryData(flag: "🇧🇧", name: "Barbados"),
        CountryData(flag: "🇧🇾", name: "Belarus"),
        CountryData(flag: "🇧🇪", name: "Belgium"),
        CountryData(flag: "🇧🇿", name: "Belize"),
        CountryData(flag: "🇧🇯", name: "Benin"),
        CountryData(flag: "🇧🇹", name: "Bhutan"),
        CountryData(flag: "🇧🇴", name: "Bolivia"),
        CountryData(flag: "🇧🇦", name: "Bosnia and Herzegovina"),
        CountryData(flag: "🇧🇼", name: "Botswana"),
        CountryData(flag: "🇧🇷", name: "Brazil"),
        CountryData(flag: "🇧🇳", name: "Brunei"),
        CountryData(flag: "🇧🇬", name: "Bulgaria"),
        CountryData(flag: "🇧🇫", name: "Burkina Faso"),
        CountryData(flag: "🇧🇮", name: "Burundi"),
        CountryData(flag: "🇰🇭", name: "Cambodia"),
        CountryData(flag: "🇨🇲", name: "Cameroon"),
        CountryData(flag: "🇨🇦", name: "Canada"),
        CountryData(flag: "🇨🇻", name: "Cabo Verde"),
        CountryData(flag: "🇨🇫", name: "Central African Republic"),
        CountryData(flag: "🇹🇩", name: "Chad"),
        CountryData(flag: "🇨🇱", name: "Chile"),
        CountryData(flag: "🇨🇳", name: "China"),
        CountryData(flag: "🇨🇴", name: "Colombia"),
        CountryData(flag: "🇰🇲", name: "Comoros"),
        CountryData(flag: "🇨🇷", name: "Costa Rica"),
        CountryData(flag: "🇭🇷", name: "Croatia"),
        CountryData(flag: "🇨🇺", name: "Cuba"),
        CountryData(flag: "🇨🇾", name: "Cyprus"),
        CountryData(flag: "🇨🇿", name: "Czech Republic"),
        CountryData(flag: "🇨🇩", name: "DRC"),
        CountryData(flag: "🇩🇰", name: "Denmark"),
        CountryData(flag: "🇩🇯", name: "Djibouti"),
        CountryData(flag: "🇩🇲", name: "Dominica"),
        CountryData(flag: "🇩🇴", name: "Dominican Republic"),
        CountryData(flag: "🇪🇨", name: "Ecuador"),
        CountryData(flag: "🇪🇬", name: "Egypt"),
        CountryData(flag: "🇸🇻", name: "El Salvador"),
        CountryData(flag: "🇬🇶", name: "Equatorial Guinea"),
        CountryData(flag: "🇪🇷", name: "Eritrea"),
        CountryData(flag: "🇪🇪", name: "Estonia"),
        CountryData(flag: "🇸🇿", name: "Eswatini"),
        CountryData(flag: "🇪🇹", name: "Ethiopia"),
        CountryData(flag: "🇫🇯", name: "Fiji"),
        CountryData(flag: "🇫🇮", name: "Finland"),
        CountryData(flag: "🇫🇷", name: "France"),
        CountryData(flag: "🇬🇦", name: "Gabon"),
        CountryData(flag: "🇬🇲", name: "Gambia"),
        CountryData(flag: "🇬🇪", name: "Georgia"),
        CountryData(flag: "🇩🇪", name: "Germany"),
        CountryData(flag: "🇬🇭", name: "Ghana"),
        CountryData(flag: "🇬🇷", name: "Greece"),
        CountryData(flag: "🇬🇩", name: "Grenada"),
        CountryData(flag: "🇬🇹", name: "Guatemala"),
        CountryData(flag: "🇬🇳", name: "Guinea"),
        CountryData(flag: "🇬🇼", name: "Guinea-Bissau"),
        CountryData(flag: "🇬🇾", name: "Guyana"),
        CountryData(flag: "🇭🇹", name: "Haiti"),
        CountryData(flag: "🇭🇳", name: "Honduras"),
        CountryData(flag: "🇭🇺", name: "Hungary"),
        CountryData(flag: "🇮🇸", name: "Iceland"),
        CountryData(flag: "🇮🇳", name: "India"),
        CountryData(flag: "🇮🇩", name: "Indonesia"),
        CountryData(flag: "🇮🇷", name: "Iran"),
        CountryData(flag: "🇮🇶", name: "Iraq"),
        CountryData(flag: "🇮🇪", name: "Ireland"),
        CountryData(flag: "🇮🇱", name: "Israel"),
        CountryData(flag: "🇮🇹", name: "Italy"),
        CountryData(flag: "🇯🇲", name: "Jamaica"),
        CountryData(flag: "🇯🇵", name: "Japan"),
        CountryData(flag: "🇯🇴", name: "Jordan"),
        CountryData(flag: "🇰🇿", name: "Kazakhstan"),
        CountryData(flag: "🇰🇪", name: "Kenya"),
        CountryData(flag: "🇰🇮", name: "Kiribati"),
        CountryData(flag: "🇰🇼", name: "Kuwait"),
        CountryData(flag: "🇰🇬", name: "Kyrgyzstan"),
        CountryData(flag: "🇱🇦", name: "Laos"),
        CountryData(flag: "🇱🇻", name: "Latvia"),
        CountryData(flag: "🇱🇧", name: "Lebanon"),
        CountryData(flag: "🇱🇸", name: "Lesotho"),
        CountryData(flag: "🇱🇷", name: "Liberia"),
        CountryData(flag: "🇱🇾", name: "Libya"),
        CountryData(flag: "🇱🇮", name: "Liechtenstein"),
        CountryData(flag: "🇱🇹", name: "Lithuania"),
        CountryData(flag: "🇱🇺", name: "Luxembourg"),
        CountryData(flag: "🇲🇬", name: "Madagascar"),
        CountryData(flag: "🇲🇼", name: "Malawi"),
        CountryData(flag: "🇲🇾", name: "Malaysia"),
        CountryData(flag: "🇲🇻", name: "Maldives"),
        CountryData(flag: "🇲🇱", name: "Mali"),
        CountryData(flag: "🇲🇹", name: "Malta"),
//        CountryData(flag: "🇲🇭", name: "Marshall Islands"),
        CountryData(flag: "🇲🇷", name: "Mauritania"),
        CountryData(flag: "🇲🇺", name: "Mauritius"),
        CountryData(flag: "🇲🇽", name: "Mexico"),
        CountryData(flag: "🇫🇲", name: "Micronesia"),
        CountryData(flag: "🇲🇩", name: "Moldova"),
        CountryData(flag: "🇲🇨", name: "Monaco"),
        CountryData(flag: "🇲🇳", name: "Mongolia"),
        CountryData(flag: "🇲🇪", name: "Montenegro"),
        CountryData(flag: "🇲🇦", name: "Morocco"),
        CountryData(flag: "🇲🇿", name: "Mozambique"),
        CountryData(flag: "🇲🇲", name: "Myanmar"),
        CountryData(flag: "🇳🇦", name: "Namibia"),
        CountryData(flag: "🇳🇵", name: "Nepal"),
        CountryData(flag: "🇳🇱", name: "Netherlands"),
        CountryData(flag: "🇳🇿", name: "New Zealand"),
        CountryData(flag: "🇳🇮", name: "Nicaragua"),
        CountryData(flag: "🇳🇪", name: "Niger"),
        CountryData(flag: "🇳🇬", name: "Nigeria"),
        CountryData(flag: "🇰🇵", name: "North Korea"),
        CountryData(flag: "🇲🇰", name: "North Macedonia"),
        CountryData(flag: "🇳🇴", name: "Norway"),
        CountryData(flag: "🇴🇲", name: "Oman"),
        CountryData(flag: "🇵🇰", name: "Pakistan"),
        CountryData(flag: "🇵🇦", name: "Panama"),
        CountryData(flag: "🇵🇬", name: "Papua New Guinea"),
        CountryData(flag: "🇵🇾", name: "Paraguay"),
        CountryData(flag: "🇵🇪", name: "Peru"),
        CountryData(flag: "🇵🇭", name: "Philippines"),
        CountryData(flag: "🇵🇱", name: "Poland"),
        CountryData(flag: "🇵🇹", name: "Portugal"),
        CountryData(flag: "🇶🇦", name: "Qatar"),
        CountryData(flag: "🇷🇴", name: "Romania"),
        CountryData(flag: "🇷🇺", name: "Russia"),
        CountryData(flag: "🇷🇼", name: "Rwanda"),
//        CountryData(flag: "🇰🇳", name: "Saint Kitts and Nevis"),
        CountryData(flag: "🇱🇨", name: "Saint Lucia"),
        CountryData(flag: "🇼🇸", name: "Samoa"),
//        CountryData(flag: "🇸🇲", name: "San Marino"),
        CountryData(flag: "🇸🇹", name: "Sao Tome and Principe"),
        CountryData(flag: "🇸🇦", name: "Saudi Arabia"),
        CountryData(flag: "🇸🇳", name: "Senegal"),
        CountryData(flag: "🇷🇸", name: "Serbia"),
        CountryData(flag: "🇸🇨", name: "Seychelles"),
        CountryData(flag: "🇸🇱", name: "Sierra Leone"),
        CountryData(flag: "🇸🇬", name: "Singapore"),
        CountryData(flag: "🇸🇰", name: "Slovakia"),
        CountryData(flag: "🇸🇮", name: "Slovenia"),
        CountryData(flag: "🇸🇧", name: "Solomon Islands"),
        CountryData(flag: "🇸🇴", name: "Somalia"),
        CountryData(flag: "🇿🇦", name: "South Africa"),
        CountryData(flag: "🇰🇷", name: "South Korea"),
        CountryData(flag: "🇸🇸", name: "South Sudan"),
        CountryData(flag: "🇪🇸", name: "Spain"),
        CountryData(flag: "🇱🇰", name: "Sri Lanka"),
        CountryData(flag: "🇸🇩", name: "Sudan"),
        CountryData(flag: "🇸🇷", name: "Suriname"),
        CountryData(flag: "🇸🇪", name: "Sweden"),
        CountryData(flag: "🇨🇭", name: "Switzerland"),
        CountryData(flag: "🇸🇾", name: "Syria"),
        CountryData(flag: "🇹🇼", name: "Taiwan"),
        CountryData(flag: "🇹🇯", name: "Tajikistan"),
        CountryData(flag: "🇹🇿", name: "Tanzania"),
        CountryData(flag: "🇹🇭", name: "Thailand"),
        CountryData(flag: "🇹🇱", name: "Timor-Leste"),
        CountryData(flag: "🇹🇬", name: "Togo"),
        CountryData(flag: "🇹🇴", name: "Tonga"),
        CountryData(flag: "🇹🇹", name: "Trinidad and Tobago"),
        CountryData(flag: "🇹🇳", name: "Tunisia"),
        CountryData(flag: "🇹🇷", name: "Turkey"),
        CountryData(flag: "🇹🇲", name: "Turkmenistan"),
        CountryData(flag: "🇺🇬", name: "Uganda"),
        CountryData(flag: "🇺🇦", name: "Ukraine"),
        CountryData(flag: "🇦🇪", name: "UAE"),
        CountryData(flag: "🇬🇧", name: "U.K."),
        CountryData(flag: "🇺🇸", name: "U.S."),
        CountryData(flag: "🇺🇾", name: "Uruguay"),
        CountryData(flag: "🇺🇿", name: "Uzbekistan"),
        CountryData(flag: "🇻🇺", name: "Vanuatu"),
        CountryData(flag: "🇻🇪", name: "Venezuela"),
        CountryData(flag: "🇻🇳", name: "Vietnam"),
        CountryData(flag: "🇾🇪", name: "Yemen"),
        CountryData(flag: "🇿🇲", name: "Zambia"),
        CountryData(flag: "🇿🇼", name: "Zimbabwe")
    ]
    
    private init () {}
}
