//
//  Languages.swift
//  Scoop
//
//  Created by Art Ostin on 18/01/2026.
//

import Foundation

enum WorldLanguages {
    static let top120Alphabetical: [String] = [
        "English",
        "French",
        "Chinese",
        "Hindi",
        "Spanish",
        "Arabic",
        "Italian",
        "Russian",
        "Portuguese",
        "Afrikaans",
        "Albanian",
        "Amharic",
        "Armenian",
        "Assamese",
        "Aymara",
        "Azerbaijani",
        "Balochi",
        "Bambara",
        "Bashkir",
        "Basque",
        "Belarusian",
        "Bengali",
        "Berber",
        "Bhojpuri",
        "Bosnian",
        "Bulgarian",
        "Burmese",
        "Catalan",
        "Cebuano",
        "Chechen",
        "Chichewa",
        "Croatian",
        "Czech",
        "Danish",
        "Dutch",
        "Estonian",
        "Ewe",
        "Finnish",
        "Fula",
        "Galician",
        "Ganda",
        "Georgian",
        "German",
        "Greek",
        "Guarani",
        "Haitian",
        "Hausa",
        "Hebrew",
        "Hiligaynon",
        "Hungarian",
        "Icelandic",
        "Igbo",
        "Ilocano",
        "Indonesian",
        "Irish",
        "Japanese",
        "Javanese",
        "Kannada",
        "Kazakh",
        "Khmer",
        "Kikongo",
        "Kinyarwanda",
        "Kirundi",
        "Korean",
        "Kurdish",
        "Kyrgyz",
        "Lao",
        "Latvian",
        "Lingala",
        "Lithuanian",
        "Luxembourgish",
        "Macedonian",
        "Madurese",
        "Malay",
        "Malayalam",
        "Marathi",
        "Maya",
        "Mongolian",
        "Nahuatl",
        "Nepali",
        "Norwegian",
        "Odia",
        "Oromo",
        "Pashto",
        "Persian",
        "Polish",
        "Punjabi",
        "Quechua",
        "Romanian",
        "Scottish",
        "Serbian",
        "Shona",
        "Sindhi",
        "Sinhala",
        "Slovak",
        "Slovenian",
        "Somali",
        "Sundanese",
        "Swahili",
        "Swedish",
        "Tagalog",
        "Tajik",
        "Tamil",
        "Tatar",
        "Telugu",
        "Thai",
        "Tigrinya",
        "Turkish",
        "Turkmen",
        "Twi",
        "Ukrainian",
        "Urdu",
        "Uyghur",
        "Uzbek",
        "Vietnamese",
        "Welsh",
        "Wolof",
        "Xhosa",
        "Yoruba",
        "Zulu"
    ]
}






